# File: .github/workflows/snake.yml
name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # runs daily at midnight UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate snake gif
    steps:
      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - name: push snake contribution graph
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output  # 🛑 make sure this matches your branch
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
